# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Wisecow
tagline:             'in the green field'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Hyunwoo Lee
  url:               https://twitter.com/mdo
  email:             twowisecow@gmail.com

# Custom vars
version:             1.0.0
